-- Reset Table
DROP TABLE IF EXISTS public.users;

-- Create Users Table with Password
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL DEFAULT '1234', -- Default password
    email TEXT NOT NULL,
    phone_number TEXT,
    position TEXT,
    team TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Seed Data with Default Password '1234'
INSERT INTO public.users (username, password, email, phone_number, position, team) VALUES
('rahayu w', '1234', 'rahayuw@gmail.com', '628123456789', 'team leader', 'PDEJP'),
('Maya', '1234', 'Tmaya@gmail.com', '62877662277', 'team member', 'PDEJP'),
('Hesti', '1234', 'hesti@gmail.com', '62876273973973', 'team member', 'PDEJP'),
('fatin', '1234', 'fatin@gmail.com', '62364897489', 'team member', 'PDEJP'),
('risti', '1234', 'risti@gmail.com', '6280088131', 'team member', 'PDEJP'),
('sadiro', '1234', 'gugliimpietro@gmail.com', '62888209848', 'team member', 'PDEJP');
